<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true"
    CodeFile="ManageTypes.aspx.cs" Inherits="ManageTypesPage" %>

<asp:Content ID="Content" ContentPlaceHolderID="ContentPlaceHolderMain" runat="Server">
    <table style="width: 100%;">
        <tr>
            <td >
               <asp:UpdatePanel ID="UpdatePanelItemTypes" runat="server" UpdateMode="Conditional">
        <ContentTemplate>
            <asp:GridView ID="GridViewItemTypes" runat="server" DataSourceID="ObjectDataSourceItemTypes"
                OnSelectedIndexChanged="GridViewItemTypes_SelectedIndexChanged" AutoGenerateColumns="False"
                AutoGenerateSelectButton="True" Caption="Item types:" DataKeyNames="Id" 
                    AutoGenerateDeleteButton="True" 
                onrowcreated="GridViewItemTypes_RowCreated" 
                onrowdeleted="GridViewItemTypes_RowDeleted">
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True"
                        SortExpression="Id" Visible="False" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                </Columns>
            </asp:GridView>
            <hr />

            <asp:DetailsView ID="DetailsViewAddItemType" runat="server" DataSourceID="ObjectDataSourceItemTypes"
                DefaultMode="Insert" AutoGenerateInsertButton="True" AutoGenerateRows="False"
                DataKeyNames="Id"
                Caption="Add new item's type:">
                <Fields>
                    <asp:BoundField InsertVisible="False" DataField="Id" HeaderText="Id" SortExpression="Id" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                </Fields>
            </asp:DetailsView>
        </ContentTemplate>
    </asp:UpdatePanel>
            </td>
            <td style="background-color: Aqua; width:10px" ></td>
            <td>
<!-- Panel for view and editing of fields-->
   <asp:UpdatePanel ID="UpdatePanelFieldTypes" runat="server">
        <ContentTemplate>
            <asp:GridView ID="GridViewFieldTypes" runat="server" EmptyDataText="Item type has no field."
                AutoGenerateColumns="False" Caption="Fields of selected item type:" DataKeyNames="Id"
               DataSourceID="ObjectDataSourceFieldTypes"
                >
                <Columns>
                    <asp:BoundField DataField="Id" Visible="false" HeaderText="Id" SortExpression="Id" />
                    <asp:BoundField DataField="ItemTypeId" Visible="false" HeaderText="ItemTypeId" SortExpression="ItemTypeId" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="TypeOfField" HeaderText="TypeOfField" SortExpression="TypeOfField" />
                </Columns>
            </asp:GridView>
                        <hr />
            <asp:DetailsView ID="DetailsViewFieldType" runat="server" DataSourceID="ObjectDataSourceFieldTypes"
                DefaultMode="Insert" DataKeyNames="Id" AutoGenerateInsertButton="True" AutoGenerateRows="False"
                OnItemInserting="DetailsViewFieldType_ItemInserting" 
                Caption="Add new field to currently selected type:" 
>
                <Fields>
                    <asp:BoundField InsertVisible="False" DataField="Id" HeaderText="Id" SortExpression="Id"
                        ReadOnly="true" />
                    <asp:TemplateField InsertVisible="False" HeaderText="ItemTypeId" SortExpression="ItemTypeId">
                        <InsertItemTemplate>
                            <asp:Literal ID="LiteralItemTypeId" Text="<%#GridViewItemTypes.SelectedValue%>" runat="server" />
                        </InsertItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:TemplateField HeaderText="TypeOfField">
                        <InsertItemTemplate >
                            <asp:DropDownList ID="DropDownListFieldType" runat="server" DataSource="<%# TypeOfField.GetSupportedTypes() %>"
                                SelectedValue="<%# TypeOfField.GetSupportedTypes()[0] %>">
                            </asp:DropDownList>
                        </InsertItemTemplate>
                    </asp:TemplateField>
                </Fields>
            </asp:DetailsView>
        </ContentTemplate>
        <Triggers>
            <asp:AsyncPostBackTrigger ControlID="GridViewItemTypes" 
                EventName="RowDeleted" />
        </Triggers>
    </asp:UpdatePanel>
            </td>
        </tr>
    </table>
    
    
    <!--Data sources-->
    <asp:ObjectDataSource ID="ObjectDataSourceItemTypes" runat="server" TypeName="ItemTypeDAO"
        DataObjectTypeName="ItemType" SelectMethod="GetAllItemTypes" 
        InsertMethod="AddItemType" OldValuesParameterFormatString="original_{0}"
        DeleteMethod="DeleteItemType"
        >
        <DeleteParameters>
            <asp:Parameter Direction="Input"  Name="id" Type="Int32" Size="4" 
                DefaultValue="" />
        </DeleteParameters>
    </asp:ObjectDataSource>
    
    <asp:ObjectDataSource ID="ObjectDataSourceFieldTypes" runat="server" TypeName="FieldTypeDAO"
        DataObjectTypeName="FieldType" SelectMethod="GetFieldTypesForItemTypeById" 
        InsertMethod="AddFieldType" 
        oninserting="ObjectDataSourceFieldTypes_Inserting" 
        onselecting="ObjectDataSourceFieldTypes_Selecting">
        <UpdateParameters>

        </UpdateParameters>
        <SelectParameters>
        <asp:ControlParameter ControlID="GridViewItemTypes" Direction="Input" PropertyName="SelectedValue" Name="itemTypeId" />

        </SelectParameters>
        <InsertParameters>
            <asp:Parameter Direction="ReturnValue" Name="id" Type="Int32" Size="4" 
                DefaultValue="" />
        </InsertParameters>
    </asp:ObjectDataSource>
</asp:Content>


