apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elastic-tracing
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 2 # at least some safety
    #name: elastic-tracing 
    config:
      node.master: true
      node.data: true
      node.ingest: true
      xpack.security.authc:
        anonymous:
          username: anonymous_user
          roles:  superuser 
          authz_exception: true 
      # is not user configurable
      # xpack.security.http.ssl.enabled: false
      #xpack.security.transport.filter.allow: _all
      #xpack.security.http.filter.allow: _all     
      #xpack.security.transport.filter.allow: '*'
      #xpack.security.http.filter.allow: '*'      
      # xpack.security.transport.filter.enabled: false
      # xpack.security.http.filter.enabled: false       
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        #storageClassName: standard # can be any available storage class      
    http:
        tls:
            selfSignedCertificate:
                disabled: true